# Copyright 2020 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: scrumlaunch2-dev-cert-participants
spec:
  domains:
    - participants.scrumlaunch2-dev.providencemt.com
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: scrumlaunch2-dev-cert-studies
spec:
  domains:
    - studies.scrumlaunch2-dev.providencemt.com
